### ISSUE TITLE
Build result update is possibly slow/racy

### ISSUE THREAD

**Issue by tjtelan** [level11consulting/orbitalci#180]
While validating if vagrant instances successfully build (PR #173) Evan and I experienced different sets of behavior, with the same inputs.

My first build status changes from RUNNING to PASS after completion in seconds, while his build has once taken a lot more time (at least a few minutes longer) before eventually changing status. There's an anomaly here.

Essentially, this was the ocelot.yml for the build:

```
image: docker
buildTool: docker
branches:
  - master
env: []
stages:
  - name: "Test"
    trigger:
      branches: []
    script:
      - echo "Hello world!"
    env: []
```

It is maybe also of note that we are using different models of macbooks. I'm using the 2015 model, and Evan has one with the touchbar. I mention this because we noticed different default behavior from terraform where it ran deployment parallel by default, where mine is serial by default. This could be behavior that I'm just not going to be able to experience hands-on with the same frequency.
