### ISSUE TITLE
Option for forcing downloads / integrations of tools 

### ISSUE THREAD

**Issue by shankj3** [level11consulting/orbitalci#89]
Need an option in the ocelot file to tell the BinaryIntegrator/StringIntegrator that this specific integration is relevant. right now IsRelevant usually checks strings in the script lines to see if that tool is called. If the tool is called from a script that lives in the repository, ocelot has no way of knowing that the integration action needs to occur. 

---
Example at root of ocelot.yml file: 
```yaml
image: golang:latest
buildTool: go
forceIntegrations:
 - mc
 - helm 
 - kubectl 
```

this will download the minio client, helm, and kubectl even if it isn't in the script lines of the ocelot.yml file
